USE smningatreinamentogrupo1

-- CRIANDO A TABELA CADASTRO EMPRESA
CREATE TABLE CadastroEmpresa (
	Id INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR(200) NOT NULL,
	Cnpj VARCHAR(13) NOT NULL,
	NomeFantasia VARCHAR(200),
	InscricaoEstadual BIGINT,
	InscricaoMunicipal BIGINT NOT NULL,
	Email VARCHAR(250) NOT NULL,
	TelefoneFixo VARCHAR(15) NOT NULL,
	DddTelefoneFixo VARCHAR(5) NOT NULL
	) 

-- CRIANDO A TABELA CNAE
CREATE TABLE Cnae (
	Id INT PRIMARY KEY IDENTITY,
	Codigo VARCHAR(7) NOT NULL,
	Descricao VARCHAR(50)
	)

-- CRIANDO A TABELA CADASTRO EMPRESA CNAE
CREATE TABLE CadastroEmpresaCnae (
	IdCadastroEmpresa INT NOT NULL,
	IdCnae INT NOT NULL,
	Principal BIT NOT NULL,
	PRIMARY KEY (IdCadastroEmpresa, IdCnae),
	FOREIGN KEY (IdCadastroEmpresa) REFERENCES CadastroEmpresa(Id),
	FOREIGN KEY (IdCnae) REFERENCES Cnae(Id)
	)

-- CRIANDO A TABELA RANKING
CREATE TABLE Ranking (
	Id INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	Valor MONEY NOT NULL
	)

-- CRIANDO A TABELA TIPO PREMIAÇÃO 
CREATE TABLE TipoPremiacao (
	Id INT PRIMARY KEY IDENTITY,
	NomePremiacao VARCHAR(50) NOT NULL
	)

-- CRIANDO A TABELA PREMIAÇÃO
CREATE TABLE Premiacao (
	Id INT PRIMARY KEY IDENTITY,
	IdRanking INT NOT NULL,
	IdCadastroEmpresa INT NOT NULL,
	IdTipoPremiacao INT NOT NULL,
	PremiacaoAtual MONEY  NULL,
	Mes TINYINT NOT NULL,
	Ano SMALLINT NOT NULL,
	FOREIGN KEY (IdRanking) REFERENCES Ranking(Id),
	FOREIGN KEY (IdCadastroEmpresa) REFERENCES CadastroEmpresa(Id),
	FOREIGN KEY (IdTipoPremiacao) REFERENCES TipoPremiacao(Id)
	)






